# Generated by Django 2.0.1 on 2018-01-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180129_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='general',
            new_name='genre',
        ),
    ]
