# Generated by Django 2.0.1 on 2018-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180214_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=500),
        ),
    ]
