# Generated by Django 2.0.1 on 2018-02-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180222_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
