# Generated by Django 2.0.1 on 2018-02-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_auto_20180225_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='默认列表<django.db.models.fields.AutoField>', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='albums_favorite',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='songs_favorite',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='albums_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='_favoritelist_albums_favorite_+', to='music.Album'),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='songs_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='_favoritelist_songs_favorite_+', to='music.Song'),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
