# Generated by Django 2.0.1 on 2018-02-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20180226_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
    ]
