# Generated by Django 2.0.1 on 2018-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20180226_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='albums_favorite',
            field=models.ManyToManyField(blank=True, related_name='_favoritelist_albums_favorite_+', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='songs_favorite',
            field=models.ManyToManyField(blank=True, related_name='_favoritelist_songs_favorite_+', to='music.Song'),
        ),
    ]
