# Generated by Django 2.1.2 on 2018-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20180301_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_bcakpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
