# Generated by Django 2.1.2 on 2018-10-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_album_album_bcakpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_bcakpic',
            new_name='album_backpic',
        ),
    ]
